app = "parlinfo-search-agent"
primary_region = "syd"
kill_signal = "SIGTERM"

[build]

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "parlinfo-search-agent.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048
  min_machines_running = 1
